services:
    auto_serwis.test:
        class: AutoSerwisBundle\Twig\Extension\ServiceExtension
        arguments: ["@doctrine"]
        tags:
            - { name: twig.extension }
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.form.registration:
        class: AutoSerwisBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
